spring:
  application:
    name: terrible-batch-service

batch:
  directory:
    default: ""
    delay: 60000
  cleaner:
    delay: 60000
  thumbnails:
    default: "/home/chris/.terrible/thumbnails/"
    delay: 60000
  search:
    delay: 60000

search:
  host: "localhost"
  port: 9200
  scheme: "http"

---
spring:
  profiles: production
  data:
    mongodb:
      host: terrible-mongo

batch:
  directory:
    default: "/terrible/terrible-media/"
  thumbnails:
    default: "/terrible/terrible-thumbnails/"

search:
  host: "terrible-search"
