spring:
  application:
    name: terrible-batch-service
  main:
    allow-bean-definition-overriding: true

server:
  port: 8090

batch:
  delay: 60000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
