spring:
  application:
    name: terrible-batch-service

batch:
  directory:
    delay: 60000
  cleaner:
    delay: 70000
  thumbnails:
    delay: 80000

---
spring:
  profiles: production
  data:
    mongodb:
      host: terrible-mongo
