spring:
  application:
    name: terrible-batch-service
  data:
    mongodb:
      host: 192.168.0.10

server:
  shutdown: graceful

batch:
  directory:
    default: "${HOME}/.terrible/media/"
    delay: 900000
  cleaner:
    delay: 900000
  thumbnails:
    default: "${HOME}/.terrible/thumbnails/"
    delay: 900000
  search:
    delay: 900000

search:
  scheme: "http"
  host: "192.168.0.10"
  port: 9200

---
spring:
  profiles: production
  data:
    mongodb:
      host: terrible-mongo

batch:
  directory:
    default: "/terrible/terrible-media/"
  thumbnails:
    default: "/terrible/terrible-thumbnails/"

search:
  host: "terrible-search"
