spring:
  application:
    name: terrible-batch-service

batch:
  directory:
    default: ""
    delay: 60000
  cleaner:
    delay: 70000
  thumbnails:
    default: "/home/chris/.terrible/thumbnails/"
    delay: 80000

---
spring:
  profiles: production
  data:
    mongodb:
      host: terrible-mongo

batch:
  directory:
    default: "/terrible/terrible-media/"
  thumbnails:
    default: "/terrible/terrible-thumbnails/"
